# [settings]
# bind_pnp_server = "0.0.0.0"
# bind_pnp_server = "::"
# port = 8080
# time_format = "%y-%m-%dt%h:%m:%s"
# status_refresh = 10
# debug = false
# log_to_file = true
# log_file = "log/pnp_debug.log"
# default_cfg_file = "default.cfg"
# no_default_cfg = false
# image_data = "images.toml"
# image_url = "http://192.168.10.133:9191/images"
# config_url = "http://192.168.10.133:9191/configs"
# default_cfg = "DEFAULT.cfg"
# mapping_file = "../LanETS - Inventaire Switch.csv"
# hostname_from_config = true
# state_file = "log/pnp_state.json"