# [settings]
# BIND_PNP_SERVER = "0.0.0.0"
# BIND_PNP_SERVER = "::"
# PORT = 8080
# TIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
STATUS_REFRESH = 10
# DEBUG = false
# LOG_TO_FILE = true
# LOG_FILE = "log/pnp_debug.log"
# DEFAULT_CFG_FILE = "DEFAULT.cfg"
# IMAGE_DATA = "images.json"
IMAGE_BASE_URL = "http://192.168.10.133:8080/images"
CONFIG_BASE_URL = "http://192.168.10.133:8080/configs"
